source 'https://rubygems.org'


gem 'rails'
gem 'rails-api'
gem 'mongoid', '~> 4.0.0.beta1', github: 'mongoid/mongoid'

gem 'foreman'
gem 'unicorn'

group :test do
  gem 'rspec-rails'
  gem 'database_cleaner'
end
