source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.1.0'
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0',          group: :doc

gem 'mongoid', '~> 4.0.0.beta1', github: 'mongoid/mongoid'

gem 'foreman'
gem 'unicorn'

group :test do
  gem 'rspec-rails'
  gem 'database_cleaner'
end

gem 'debugger'
