source 'https://rubygems.org'


gem 'sinatra'
gem 'mongoid', '~> 4.0.0.beta1', github: 'mongoid/mongoid'

gem 'foreman'
gem 'unicorn'

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'database_cleaner'
  gem 'debugger'
end
